[package]
name = "block_macro"
version = "0.1.0"
authors = ["Federico Perez <fedemperez@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.4.0"
serde_json = "1.0.64"
